name: BucketDesignApp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
    
flutter:
  uses-material-design: true

  fonts:
   - family: Manrope
     fonts:
      - asset: assets/fonts/manrope-regular.otf
        weight: 400
      - asset: assets/fonts/manrope-thin.otf
        weight: 100
      - asset: assets/fonts/manrope-light.otf
        weight: 300
      - asset: assets/fonts/manrope-medium.otf
        weight: 500
      - asset: assets/fonts/manrope-semibold.otf
        weight: 600
      - asset: assets/fonts/manrope-bold.otf
        weight: 700
      - asset: assets/fonts/manrope-extrabold.otf
        weight: 800
   - family: CustomIcons
     fonts:
      - asset: assets/fonts/CustomIcons.ttf